spring:
  application:
    name: SPRING-REST
  profiles:
    active: production
  datasource:
    generate-unique-name: false
    name: members-db
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show_sql: true
    properties:
      hibernate:
        generate_statistics: true
---
spring:
  config:
    activate:
      on-profile: disable-security
---
spring:
  config:
    config:
      activate:
        on-profile: production
logging:
  level:
    root: OFF

